#!/bin/bash
#
# USAGE: ii FILE [COMMAND]
#  DESC: Invisible ink.
#        Decrypt or create the given FILE. COMMAND will be run on the
#        cleartext. When COMMAND exits, the cleartext will be re-encrypted.
#        The default command is 'EDITOR', in which case the value of the
#        $EDITOR variable will be used as the actual command.
#    BY: Macquarie Sharpless <macquarie.sharpless@gmail.com> 2014
#        grimheart.github.com



# Generic error handler
function err {
	local msg=${@}
	echo "Error: ${msg}"
	expunge
	exit 1
}

# Remove the temporary directory
function expunge {
	rm -rf "${II_TEMPDIR}" &> /dev/null
}



II_FILE=${1}
[ -z "${II_FILE}" ] && err "no path given"
II_CMD=${2}
[ -z "${II_CMD}" ] && II_CMD="EDITOR"

II_TEMPDIR=$(mktemp -dt "invisibleink.XXXX")
II_CLEARFILE="${II_TEMPDIR}/text"
II_KEYUID="invisibleink"



# Decrypt the given file if it already exists
if [ -e ${II_FILE} ]; then
	gpg -q -r ${II_KEYUID} --output ${II_CLEARFILE} -d ${II_FILE} || err "decryption failed"
fi

case ${II_CMD} in
  # The 'EDITOR' command is the default command; rather than a specific
  # program, it will use your $EDITOR to edit the cleartext.
  "EDITOR")
    # Edit the cleartext file
    ${EDITOR} ${II_CLEARFILE}
  ;;
  *)
    # Run an arbitrary command over the cleartext file
    ${II_CMD} ${II_CLEARFILE}
  ;;
esac

# (Re-)encrypt the (edited?) cleartext
gpg -r ${II_KEYUID} -e ${II_CLEARFILE}
cat ${II_CLEARFILE}.gpg > ${II_FILE}

# Expunge the cleartext and temporary files
expunge

